clear
MainTimeDomain_Kvec_Glyc
figure
hold on
plot(Results{1,1}(:,1),Results{1,1}(:,12), 'b-', ...   
    Results{1,2}(:,1),Results{1,2}(:,12), 'r-', ...
    Results{1,3}(:,1),Results{1,3}(:,12), 'g-', ...
    'LineWidth', 3)

%Results{1,2}(:,1),Results{1,2}(:,7), 'g-', ...
%Results{1,2}(:,1),Results{1,2}(:,5), 'g:', ...

% legend({'1x Feed', ...
%     '2x Feed', ...
%     '4x Feed'}, ...
%     'FontSize', 16, 'Position',[0.2 0.75 0.3 0.1]);
% legend('boxoff');

set(gca,'LineWidth',2, 'fontsize', 18, 'FontName', 'Cambria', 'box', 'off')
set(gca,'xtick',[0 35 70], 'xticklabel',{' ' '1' '2'})%, 'fontsize', 11, 'fontname', 'Cambria')
set(gca,'ytick',[0 90 180], 'yticklabel',{'0' ' ' '20'});%, 'fontsize', 11, 'fontname', 'Cambria')
xlabel('Time (relative)')
ylabel('Lactate Conc. (relative)')
set(gcf,'color','white')
ylim([0 180])
xlim([0 70])
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
figure
hold on
plot(Results{1,1}(:,1),Results{1,1}(:,13), 'b-', ...   
    Results{1,2}(:,1),Results{1,2}(:,13), 'r-', ...
    Results{1,3}(:,1),Results{1,3}(:,13), 'g-', ...
    'LineWidth', 3)

%Results{1,2}(:,1),Results{1,2}(:,7), 'g-', ...
%Results{1,2}(:,1),Results{1,2}(:,5), 'g:', ...

% legend({'1x Feed', ...
%     '2x Feed', ...
%     '4x Feed'}, ...
%     'FontSize', 16, 'Position',[0.2 0.75 0.3 0.1]);
% legend('boxoff');

set(gca,'LineWidth',2, 'fontsize', 18, 'FontName', 'Cambria', 'box', 'off')
set(gca,'xtick',[0 35 70 150], 'xticklabel',{' ' '1' '2'})%, 'fontsize', 11, 'fontname', 'Cambria')
set(gca,'ytick',[0 4 8], 'yticklabel',{'0' ' ' '1'});%, 'fontsize', 11, 'fontname', 'Cambria')
xlabel('Time (relative)')
ylabel('ATP Conc. (relative)')
set(gcf,'color','white')
ylim([0 8])
xlim([0 70])

% figure
% plot(Results{1,1}(:,1),Results{1,1}(:,2), 'b-', ...   
%     Results{1,3}(:,1),Results{1,3}(:,2), 'r-', ...
%     Results{1,1}(:,1),Results{1,1}(:,11), 'b--', ...
%     Results{1,3}(:,1),Results{1,3}(:,11), 'r--', ...
%     'LineWidth', 3)
% 
% ylim([0 100])
% xlim([0 150])
% 
% set(gca,'LineWidth',1, 'fontsize', 14, 'FontName', 'Cambria', 'box', 'off')
% set(gca,'xtick',[0 50 100 150])% 'xticklabel',{'1' '10'}, 'fontsize', 11, 'fontname', 'Cambria')
% set(gca,'ytick',[0 1 2]);%, 'yticklabel',{'0' '0.5' '1'});%, 'fontsize', 11, 'fontname', 'Cambria')
% xlabel('Time (relative)')
% ylabel('Metabolite Level (relative)')
% set(gcf,'color','white')
% 
% legend({'CH_2O, Stable', ...
%     'CH_2O, Unstable', ...
%     'F6P, Stable', ...
%     'F6P, Unstable'}, ...
%     'FontSize', 12, 'Position',[0.62 0.32 0.3 0.1]);
% legend('boxoff');
% 
% PlotTimeDomain_Fxpk_Big